#!/bin/bash
#
#  $Header: /home/jahn/src/cvs2git/MITgcm/20170915-2/gcmpack-all-patch/MITgcm/tools/build_options/Attic/t90,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


FC='f90'
LINK='f90'
LN='/bin/ln -s'
CPP='/opt/ctl/bin/cpp -N -P'
FOPTIM='-O0'
NOOPTFLAGS='-O0'

