#!/bin/bash

# $Header: /home/jahn/src/cvs2git/MITgcm/20170915-2/gcmpack-all-patch/MITgcm/verification/adjustment.128x64x1/input/Attic/gm_local,v 1.1 2003/08/16 14:01:08 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08

DISABLE="aim aim_v23"

ENABLE=
