#!/bin/bash

# $Header: /home/jahn/src/cvs2git/MITgcm/20170915-2/gcmpack-all-patch/MITgcm/verification/cpl_aim+ocn/build_ocn/genmake_local,v 1.1 2003/12/15 21:06:30 jmc Exp $

#  This is the local options file for the "new" version of genmake
#
#  EH3 initial version 2003-08

MODS="../code_ocn ../shared_code"
