#!/bin/bash

# $Header: /home/jahn/src/cvs2git/MITgcm/20170915-2/gcmpack-all-patch/MITgcm/verification/lab_sea/input/Attic/gm_local,v 1.1 2003/08/16 14:01:09 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08


DISABLE="aim shap_filt obcs zonal_filt autodiff cost ctrl grdchk"

ENABLE="cal exf sbo seaice gmredi kpp timeave"
